# Regression test for https://github.com/KeyWorksRW/CMakeRC2/issues/17
#
# CMakeRC used to generate cmrc/cmrc.hpp with file(GENERATE) at configure
# time, so it was not the OUTPUT/BYPRODUCTS of any add_custom_command. Ninja
# (and the CMP0058 policy check) then flagged the header as an undeclared
# build-tree file because resource loader custom commands list it in DEPENDS.
#
# This test verifies the fix: cmrc.hpp must be a real build-time product.
# It configures and builds a tiny consumer project, then deletes the
# generated header and the generated resource-loader sources and rebuilds.
# With the old code the header only ever existed because configure-time
# file(GENERATE) wrote it, so the rebuild fails with "cmrc/cmrc.hpp: No such
# file". With the fix the header is regenerated by its custom command and the
# rebuild succeeds. This works with any generator, not just Ninja.
#
# Required -D arguments:
#   CMRC_MODULE  absolute path to the real CMakeRC.cmake in the source tree
#   GEN          the generator to use for the nested configure (inherited
#                from the parent project's CMAKE_GENERATOR)
#   BIN_ROOT     scratch directory (inside the parent build tree) where the
#                nested consumer project is configured and built

if(NOT DEFINED CMRC_MODULE OR NOT DEFINED GEN OR NOT DEFINED BIN_ROOT)
    message(FATAL_ERROR "header_regen: missing required -D argument "
        "(CMRC_MODULE, GEN, BIN_ROOT)")
endif()

# Start from a clean slate so the test never depends on leftovers from an
# earlier run.
file(REMOVE_RECURSE "${BIN_ROOT}")
file(MAKE_DIRECTORY "${BIN_ROOT}")

# The nested consumer project lives in this same directory; its CMakeLists
# includes the real CMakeRC via the -DCMRC_MODULE argument passed below.
set(nested_src "${CMAKE_CURRENT_LIST_DIR}")

function(run_and_check step)
    execute_process(
        COMMAND ${CMAKE_COMMAND} ${ARGN}
        RESULT_VARIABLE result
        OUTPUT_VARIABLE output
        ERROR_VARIABLE error
        )
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "header_regen: ${step} failed (exit ${result})\n"
            "STDOUT:\n${output}\nSTDERR:\n${error}")
    endif()
    # Re-export for the caller to inspect if needed.
    set(LAST_OUTPUT "${output}" PARENT_SCOPE)
    set(LAST_ERROR "${error}" PARENT_SCOPE)
endfunction()

set(hpp "${BIN_ROOT}/build/_cmrc/include/cmrc/cmrc.hpp")

# 1. Fresh configure + build must produce cmrc.hpp and a working executable.
run_and_check("initial configure" -G "${GEN}" -S "${nested_src}" -B "${BIN_ROOT}/build"
    -DCMRC_MODULE=${CMRC_MODULE})
run_and_check("initial build" --build "${BIN_ROOT}/build")
if(NOT EXISTS "${hpp}")
    message(FATAL_ERROR "header_regen: cmrc.hpp was not generated by the build\n"
        "${hpp}")
endif()

# 2. Blow away the build-time generated products (the header and the
#    resource-loader/intermediate sources) and rebuild. The header must be
#    regenerated from its configure-time template by its custom command; the
#    old approach (where the header was itself written by configure-time
#    file(GENERATE)) cannot recover from this when the file is deleted.
file(REMOVE "${hpp}")
file(GLOB_RECURSE generated_sources "${BIN_ROOT}/build/__cmrc_*")
foreach(src IN LISTS generated_sources)
    file(REMOVE "${src}")
endforeach()
run_and_check("rebuild after deleting generated files" --build "${BIN_ROOT}/build")
if(NOT EXISTS "${hpp}")
    message(FATAL_ERROR "header_regen: rebuilding did not regenerate cmrc.hpp\n"
        "${hpp}")
endif()

# 3. The executable built in step 1 must still exist and the regenerated
#    build must not have stale products. (Running the executable is not
#    generator-neutral -- multi-config generators place it in a per-config
#    subdirectory -- so the existing executable-based tests cover actual
#    runtime behavior.)
file(GLOB_RECURSE consumer_exes "${BIN_ROOT}/build/header_regen*")
if(NOT consumer_exes)
    message(FATAL_ERROR "header_regen: consumer executable was not built\n")
endif()

message(STATUS "header_regen: OK")
